"""Loader for the bundled catalogue of non-isomorphic semigroups.

The files ``sem.2`` .. ``sem.6`` (see ``sexpansion/data/README.txt``)
contain all non-isomorphic semigroups of orders 2 to 6 in lexicographic
ordering, as generated by the Fortran program ``gen.f`` referenced in the
paper (Section 2.4). This module replaces the Java
``Semigroup.loadFromFile`` / ``loadFile`` methods.
"""

from __future__ import annotations

from functools import cache
from importlib.resources import files
from typing import Final

import numpy as np

from .semigroup import Semigroup

#: Number of non-isomorphic semigroups per catalogued order.
SEMIGROUP_COUNTS: Final[dict[int, int]] = {2: 4, 3: 18, 4: 126, 5: 1160, 6: 15973}


@cache
def load_semigroups(order: int) -> tuple[Semigroup, ...]:
    """Load every catalogued semigroup of the given order (2..6).

    Elements are converted from the files' 1-based labels to the
    package-wide 0-based convention. ``Semigroup.sem_id`` keeps the
    catalogue identifier ``a`` of the paper's ``S^a_(n)`` notation
    (1-based, as published).
    """
    if order not in SEMIGROUP_COUNTS:
        raise ValueError(f"no catalogue for order {order}; available: 2..6")
    text = files("sexpansion.data").joinpath(f"sem.{order}").read_text(encoding="ascii")
    tokens = np.array(text.split(), dtype=np.int_)
    record_len = 2 + order * order
    expected = SEMIGROUP_COUNTS[order]
    if tokens.size != expected * record_len:
        raise RuntimeError(
            f"sem.{order} is corrupt: expected {expected * record_len} tokens, got {tokens.size}"
        )
    records = tokens.reshape(expected, record_len)
    if not np.array_equal(records[:, 1], np.full(expected, order)):
        raise RuntimeError(f"sem.{order} is corrupt: order field mismatch")
    tables = records[:, 2:].reshape(expected, order, order) - 1
    return tuple(
        Semigroup(table, sem_id=int(sem_id))
        for sem_id, table in zip(records[:, 0], tables, strict=True)
    )


def load_semigroup(order: int, sem_id: int) -> Semigroup:
    """Load the catalogued semigroup ``S^sem_id_(order)`` (1-based ID)."""
    semigroups = load_semigroups(order)
    if not 1 <= sem_id <= len(semigroups):
        raise ValueError(f"sem_id must be in 1..{len(semigroups)} for order {order}")
    sg = semigroups[sem_id - 1]
    assert sg.sem_id == sem_id
    return sg


def load_all_semigroups() -> tuple[Semigroup, ...]:
    """Load the full catalogue for all orders 2..6 (Java ``loadFromFile``)."""
    result: list[Semigroup] = []
    for order in SEMIGROUP_COUNTS:
        result.extend(load_semigroups(order))
    return tuple(result)
