# 2. Counting the commutative semigroups of each order

S-expansions require **abelian** (commutative) semigroups, so a natural first question about the
catalogue of finite semigroups is: how many of each order are commutative?

This notebook ports the Java example `I_commutative_ord2_to_6` from Section 5.1 of the paper
(C. Inostroza, I. Kondrashuk, N. Merino, F. Nadal, *A Java Library to Perform S-Expansions of Lie Algebras*, Axioms (2025)). The package ships the complete catalogue of the 17,281 non-isomorphic semigroups of
orders 2–6; `load_semigroups(order)` iterates over one order and `SEMIGROUP_COUNTS` records the
catalogue sizes.

Expected counts of commutative semigroups (paper, Table 5): **3, 12, 58, 325 and 2,143** for
orders 2 through 6.

In [1]:
from sexpansion import SEMIGROUP_COUNTS, load_semigroups

## Scan the catalogue

In [2]:
for order in SEMIGROUP_COUNTS:
    commutative = [sg for sg in load_semigroups(order) if sg.is_commutative]
    print(
        f"Order {order}: {len(commutative)} of {SEMIGROUP_COUNTS[order]} "
        "non-isomorphic semigroups are commutative"
    )

Order 2: 3 of 4 non-isomorphic semigroups are commutative
Order 3: 12 of 18 non-isomorphic semigroups are commutative
Order 4: 58 of 126 non-isomorphic semigroups are commutative
Order 5: 325 of 1160 non-isomorphic semigroups are commutative
Order 6: 2143 of 15973 non-isomorphic semigroups are commutative


## Result

The counts 3, 12, 58, 325 and 2,143 reproduce Table 5 of the paper. These commutative semigroups
are the candidate ingredients for the S-expansions explored in the later notebooks.